#!/usr/bin/env php
<?php
/**
 * Copyright (c) Eduard Sukharev
 * Standard MIT License. See LICENSE.txt for full license text.
 */

require __DIR__ . '/../vendor/autoload.php';

use Rodrigodiez\Component\RichConsole\Console\Application;

$configFilenames = [
    'services.yml',
    'crawler_headers.yml',
];

$configDirs = [
    __DIR__ . '/../src/WebAnalyzer/CrawlerBundle/Resources/',
    __DIR__ . '/../app/config/',
    __DIR__ . '/src/WebAnalyzer/CrawlerBundle/Resources/',
    __DIR__ . '/app/config/',
];

$application = new Application($configDirs, $configFilenames);

$application->run();
