services:
    web_analyzer.command.analyze_page:
        class:     \WebAnalyzer\CrawlerBundle\Command\AnalyzePageCommand
        tags:
            - { name: 'console.command' }
    web_analyzer.analyzer_factory:
        class:     \WebAnalyzer\CrawlerBundle\Analyzer\AnalyzerFactory
        arguments:
            - '@logger'
            - '%analyzers%'

    log_file_handler:
        class: \Monolog\Handler\StreamHandler
        arguments: [ '%log_dir%/application.log', '%legger_level%']

    logger:
        class: \Monolog\Logger
        arguments:
            - '%application_name%'
            - [ '@log_file_handler' ]

